name: OnduraHud
version: 1.0
main: com.ondura.hud.OnduraHud
api-version: 1.21
depend: [Oraxen, PlaceholderAPI]
commands:
  ondurahud:
    description: Commande principale du plugin
    permission: ondurahud.use
    usage: /<command> reload